sudo: required

language: minimal

services:
  - docker

before_install:
  - docker build -t libtooling - < Docker/Travis.Dockerfile
  - docker run --name libtooling_build -v "${TRAVIS_BUILD_DIR}:/root/clang-llvm/llvm/tools/clang/tools/extra/find-api-usage" libtooling /root/clang-llvm/llvm/tools/clang/tools/extra/find-api-usage/Docker/docker-test.sh
